files:
  include:
    - 'src/assets/styles/**/*.scss'
rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
  no-vendor-prefixes:
    - 0
  no-transition-all:
    - 0
  nesting-depth:
    - 1
    - max-depth: 3
  leading-zero:
    - 0
  no-important:
    - 0
